name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        django-version: ["4.2", "5.0", "5.1", "5.2"]
        ospy-version: ["2.8", "3.0"]
        os-version: ["2", "3"]

    steps:
      - uses: ankane/setup-opensearch@v1
        with:
          opensearch-version: ${{ matrix.os-version }}

      - uses: actions/checkout@v4

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Enable caching
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install Dependencies
        run: |
          uv sync --locked --dev

      - name: Run tests with Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }}, OpenSearch ${{ matrix.os-version }}, opensearch-py ${{ matrix.ospy-version }}
        run: |
          tox run -e py${{ matrix.python-version }}-django${{ matrix.django-version }}-os${{ matrix.ospy-version }}
          tox run -e py${{ matrix.python-version }}-django${{ matrix.django-version }}-os${{ matrix.ospy-version }} -- --signal-processor celery
          uv run coverage xml

      - name: Coverage
        uses: ewjoachim/coverage-comment-action@v1
        with:
          GITHUB_TOKEN: ${{ github.token }}
          COVERAGE_FILE: "coverage.xml"
